env:
  browser: true
  commonjs: true
  es6: true
extends:
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  describe: readonly
  it: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  quotes: ["error", "double"]
  indent: ["error", 4]
  no-shadow: error
  camelcase: ["error", {"properties": "never"}]
